name: dart_gpx
description: JSON GPX parser.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^2.0.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1
  build_runner: ^1.0.0
  json_serializable: ^2.0.1

flutter:
